### ISSUE TITLE
Camera FoV in evaluation

### ISSUE THREAD

**Issue by haiphamcse** [ai4ce/SSCBench#12]
Hi there, thank you for your excellent work to push SSC forward. I have a question about camera vs lidar in evaluating the mIoU. Is the camera FoV considered in your formulation (since camera FoV are smaller than LiDAR), which gives LiDAR a better advantage. Furthermore what is the difference between empty and invalid voxels in your dataset. 
![image](https://github.com/ai4ce/SSCBench/assets/76871780/f56a985c-0fa1-45e9-87d4-4be040c2bdce)

**Comment by Gaaaavin** [comment]
Thank you for your interest in our work.
To answer your first question, we do not take the FoV into consideration. We believe that current camera-based methods have the ability to reason outside the FoV to some extent, though this is indeed one of the major reasons why camera-based methods are generally outperformed by LiDAR-based methods.
For the second question. Empty voxels are those traversed by at least one one LiDAR beam, and invalid voxels are those unknown ones that are not hit nor traversed by any of the LiDAR beams. Please refer to our [paper](https://arxiv.org/abs/2306.09001) for more detailed explaination.
