### ISSUE TITLE
Visualization issue using the provided pre-trained model

### ISSUE THREAD

**Issue by yyash-patel** [ai4ce/SSCBench#16]
Hi,

I am trying to visualize nuscene test data using the provided [pre-trained model](https://drive.google.com/drive/folders/156erXhGg4_n6jAX0eAk-3EFAI3wLp82c) -  of nuscene. 

I use the visualization code [generate output](https://github.com/ai4ce/SSCBench/blob/main/method/MonoScene/monoscene/scripts/generate_output.py) and to visualize I use this [script](https://github.com/astra-vision/MonoScene/blob/master/monoscene/scripts/visualization/kitti_vis_pred.py).

I make sure to use the pre-trained model by providing the appropriate path and nuscenes test dataloader, But the results are not correct.

![Screenshot 2023-11-06 211004](https://github.com/ai4ce/SSCBench/assets/145590775/aa09ac17-ea90-4d72-80de-45bb38350f03)

![Screenshot 2023-11-06 211030](https://github.com/ai4ce/SSCBench/assets/145590775/bc945781-b8b1-4552-ae9e-3e12aa3bda46)

**Comment by Gaaaavin** [comment]
For visualization, it's recommended to use the code from [SemanticKITTI](https://github.com/PRBonn/semantic-kitti-api/blob/master/visualize.py). 
There is also another adapted version in [Occ4cast](https://github.com/ai4ce/Occ4cast/blob/main/data_processing/visualization/visualize_voxels.py). Checking is as a reference can also be helpful.
