### ISSUE TITLE
Data source cross platform [baiduyun, opendatalab]

### ISSUE THREAD

**Issue by billbliss3** [ai4ce/SSCBench#2]
It is a awesome work!
Shall we extend more data source to support baiduyun and opendatalab.

**Comment by Gaaaavin** [comment]
Hi,  thank you for your interest in our dataset.
We are considering releasing the data on opendatalab.
We will have an update later once it's released.

**Comment by billbliss3** [comment]
您好，您的来件已收到，我会尽快给您回复的。

Thanks for you e-mail.~~
I've got it and I will reply it as soon as possible .

**Comment by Gaaaavin** [comment]
Close due to no further responce

**Comment by billbliss3** [comment]
Looking forward to see SSCBench on opendatalab.

**Comment by billbliss3** [comment]
> Hi, thank you for your interest in our dataset. We are considering releasing the data on opendatalab. We will have an update later once it's released.

Hi.
Do we have the plan to upload SSCBench to opendatalab?

**Comment by simbaforrest** [comment]
Hi @billbliss3 We are thinking of using huggingface. Would that be easy to access for you?

Copying @Gaaaavin @RoboticsYimingLi

**Comment by billbliss3** [comment]
您好，您的来件已收到，我会尽快给您回复的。

Thanks for you e-mail.~~
I've got it and I will reply it as soon as possible .

**Comment by billbliss3** [comment]
> Hi @billbliss3 We are thinking of using huggingface. Would that be easy to access for you?
> 
> Copying @Gaaaavin @RoboticsYimingLi

What a pity.
It seems that I cannot access to it.
