### ISSUE TITLE
Most voxels are invalid in KITTI-360

### ISSUE THREAD

**Issue by gxytcrc** [ai4ce/SSCBench#21]
Hi, thank you for providing the dataset. I am currently evaluating methods on KITTI-360 and have loaded the ..1_1.npy file from the preprocess/label folder. However, I noticed that over 80% of the voxels are labeled as invalid, including those in the air. Shouldn't these voxels be labeled as empty, with only occluded voxels marked as invalid? Here is a visualization (000000 in 06 sequences) where black voxels represent those labeled as invalid, and white voxels are labeled as empty. You can see only very few voxels are set to empty, most of them are invalid.
<img width="1682" alt="微信图片_20240930204725" src="https://github.com/user-attachments/assets/a7cd7d19-072f-47bf-85ca-3443840f40e8">
<img width="1166" alt="微信图片_20240930210428" src="https://github.com/user-attachments/assets/4a48e540-36c3-430f-a3fd-380dc3f314a6">

**Comment by Gaaaavin** [comment]
This is expected. Please refer to the paper for detailed definition of the "free" voxels. All the unprobed voxels are set to unknown. We only set those voxels that passed by at least lidar ray as free.
