### ISSUE TITLE
The id correspondence between SSCbench and KITTI360

### ISSUE THREAD

**Issue by gxytcrc** [ai4ce/SSCBench#22]
Hi, could you please provide the correspondence between SSCBench and the original KITTI360 IDs? I want to use the pose information from the original dataset's Oxts files, but I noticed that the original images and SSCBench are not perfectly aligned one-to-one.

**Comment by Gaaaavin** [comment]
Please check (this file)[https://github.com/ai4ce/SSCBench/blob/f6828ebe7f87953b0e006f10de19e85eeb1eceee/method/MonoScene/monoscene/data/kitti_360/kitti_360.yaml]
