### ISSUE TITLE
Provide predictions of the KITTI-360 Benchmark models on the test set

### ISSUE THREAD

**Issue by ahayler** [ai4ce/SSCBench#5]
Dear all,
would it be possible for you to provide the predictions on the test set of the KITTI-360 benchmark models (so MonoScene, Voxformer-S, LMSCNet and SSCNet) you have evaluated.

Kind regards,
Adrian

**Comment by Gaaaavin** [comment]
Thank you for your interest in the dataset.
At the current stage, we may not have the bandwidth to cleanup these experiment results for open access.

It is possible though to use the open-sourced code for the abovementioned methods to reproduce the result. You can also check the code for MonoScene in this repo.
We will push the code for other methods at a later stage.

**Comment by ahayler** [comment]
Would it be easier to provide the underlying models and the evaluation scripts? Reproducing the other models/results would mean a lot of redundant work, that probably wouldn't lead to the same results due to different design choices.

**Comment by Gaaaavin** [comment]
Checkpoints for each method on SSCBench can be accessed by following [instructions](https://github.com/ai4ce/SSCBench#model-checkpoints) in the README.

**Comment by ahayler** [comment]
Thank you so much! I must have glossed over that. 
Would it be also be possible for you to provide the modified dataloader/dataset classes for the other three methods. Regardless of how "cleaned up" or readable they currently are, they would provide an invaluable starting point for reconstructing the evaluations.

Kind regards,
Adrian

**Comment by Brummi** [comment]
Hi @Gaaaavin,
thank you very much for providing the checkpoints!

I checked out the drive folder and notices that the checkpoints for LMSCNet and SSCNet are very small (just a few MBs). Are these the full checkpoints or do we have to do some additional steps?

Many thanks in advance!
Best,
Felix

**Comment by Gaaaavin** [comment]
@Brummi Yes, LMSCNet and SSCNet has a much smaller checkpoint size compared to that of MonoScene

**Comment by Brummi** [comment]
Alright, thanks a lot!
