### ISSUE TITLE
Benchmarking Against KITTI-360 Results

### ISSUE THREAD

**Issue by npurson** [ai4ce/SSCBench#7]
I assume that the results of KITTI-360 in the paper were reported on the test set, but I couldn't find the test server available for submission.
Could you please confirm if the KITTI-360 test server has been released yet? If not, would it be possible to report your results on the validation set?

Please let me know if there are plans to release the test server, or if sharing results on the validation set instead is a possibility.
Thank you for your consideration!

**Comment by Gaaaavin** [comment]
Please read [README.md](https://github.com/ai4ce/SSCBench/tree/main/dataset/KITTI-360) for details of the dataset. The test sequence is included in the released dataset. Currently we do not have the plan for a test server.

**Comment by npurson** [comment]
Apologies for my oversight. Thank you for your response.
