### ISSUE TITLE
The preprocessed label files for KITTI-360 seems to miss the categories beyond 10

### ISSUE THREAD

**Issue by npurson** [ai4ce/SSCBench#9]
Upon sampling and analyzing several preprocessed label files, I discover that none of them contain classes greater than 10.

To reproduce this issue, you can follow the steps below in Python:

```python
>>> path = 'kitti_360/data_2d_raw/2013_05_28_drive_0005_sync/voxels/000500.label'
>>> np.unique(np.fromfile(path, dtype=np.uint16).astype(np.float32))
array([ 0., 10., 20., 40., 44., 48., 49., 50., 52., 70., 72., 80., 99.],
      dtype=float32)
>>> path_label = 'kitti_360/labels/2013_05_28_drive_0005_sync/000500_1_1.npy'
>>> np.unique(np.load(path_label))
array([  0.,   1.,   5.,   6.,   7.,   8.,   9.,  10., 255.],
      dtype=float32)
```

**Comment by ahayler** [comment]
I encountered the same issue and after plotting I came to the conclusion that the NuScene label map was used to generate the KITTI360 preprocessed ground truth (this also maps a lot of classes to unlabeled). You need to rerun the label preprocessing with the KITTI360 label map (they can be found in the according .yaml files).

**Comment by Gaaaavin** [comment]
The label map for KITTI-360 is now uploaded. Please use the [config file](https://github.com/ai4ce/SSCBench/blob/main/dataset/configs/kitti360.yaml) for pre-processing.
